name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run test
